modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"
issueTrackerURL="https://github.com/Iunius118/O.F.Device/issues"

[[mods]]
modId="orefarmingdevice"
version="${file.jarVersion}"
displayName="O.F.Device (Ore Farming Device)"
displayURL="https://github.com/Iunius118/O.F.Device"
logoFile="orefarmingdevice_logo.png"
credits="Iunius118"
authors="Iunius118"
description="Adds devices for farming ores"

[[dependencies.orefarmingdevice]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.orefarmingdevice]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
